// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/sykesm/kubernetes-cpi/kubecluster"
)

type ClientProvider struct {
	NewStub        func(context string) (kubecluster.Client, error)
	newMutex       sync.RWMutex
	newArgsForCall []struct {
		context string
	}
	newReturns struct {
		result1 kubecluster.Client
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ClientProvider) New(context string) (kubecluster.Client, error) {
	fake.newMutex.Lock()
	fake.newArgsForCall = append(fake.newArgsForCall, struct {
		context string
	}{context})
	fake.recordInvocation("New", []interface{}{context})
	fake.newMutex.Unlock()
	if fake.NewStub != nil {
		return fake.NewStub(context)
	} else {
		return fake.newReturns.result1, fake.newReturns.result2
	}
}

func (fake *ClientProvider) NewCallCount() int {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return len(fake.newArgsForCall)
}

func (fake *ClientProvider) NewArgsForCall(i int) string {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.newArgsForCall[i].context
}

func (fake *ClientProvider) NewReturns(result1 kubecluster.Client, result2 error) {
	fake.NewStub = nil
	fake.newReturns = struct {
		result1 kubecluster.Client
		result2 error
	}{result1, result2}
}

func (fake *ClientProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.invocations
}

func (fake *ClientProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kubecluster.ClientProvider = new(ClientProvider)
